CREATE TYPE "user_status" AS ENUM (
  'ACTIVE',
  'BLOCKED',
  'DELETED'
);

CREATE TYPE "auth_provider" AS ENUM (
  'LOCAL',
  'GOOGLE'
);

CREATE TYPE "product_status" AS ENUM (
  'DRAFT',
  'ACTIVE',
  'ARCHIVED'
);

CREATE TYPE "cart_status" AS ENUM (
  'ACTIVE',
  'CONVERTED_TO_ORDER',
  'ABANDONED'
);

CREATE TYPE "order_status" AS ENUM (
  'PENDING_PAYMENT',
  'PAID',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED',
  'REFUNDED'
);

CREATE TYPE "payment_status" AS ENUM (
  'CREATED',
  'PENDING',
  'SUCCEEDED',
  'FAILED',
  'CANCELLED',
  'PARTIALLY_REFUNDED',
  'REFUNDED'
);

CREATE TYPE "refund_status" AS ENUM (
  'PENDING',
  'SUCCEEDED',
  'FAILED',
  'CANCELLED'
);

CREATE TYPE "discount_type" AS ENUM (
  'PERCENTAGE',
  'FIXED_AMOUNT'
);

CREATE TYPE "discount_application_type" AS ENUM (
  'AUTOMATIC',
  'COUPON'
);

CREATE TYPE "inventory_movement_type" AS ENUM (
  'STOCK_IN',
  'STOCK_OUT',
  'RESERVATION',
  'RELEASE',
  'SALE',
  'RETURN',
  'MANUAL_ADJUSTMENT'
);

CREATE TYPE "address_type" AS ENUM (
  'SHIPPING',
  'BILLING'
);

CREATE TYPE "shipment_status" AS ENUM (
  'CREATED',
  'READY',
  'SHIPPED',
  'DELIVERED',
  'RETURNED',
  'CANCELLED'
);

CREATE TYPE "token_type" AS ENUM (
  'EMAIL_VERIFICATION',
  'PASSWORD_RESET'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "phone" varchar(50),
  "status" user_status NOT NULL DEFAULT 'ACTIVE',
  "email_verified" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "last_login_at" timestamp
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_roles" (
  "user_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  "assigned_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "auth_accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "provider" auth_provider NOT NULL,
  "provider_account_id" varchar(255) NOT NULL,
  "password_hash" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "auth_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token_type" token_type NOT NULL,
  "token_hash" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "guest_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_token" varchar(255) UNIQUE NOT NULL,
  "converted_user_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "expires_at" timestamp NOT NULL,
  "converted_at" timestamp
);

CREATE TABLE "addresses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "label" varchar(100),
  "address_type" address_type,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "company" varchar(150),
  "phone" varchar(50),
  "street_line_1" varchar(255) NOT NULL,
  "street_line_2" varchar(255),
  "city" varchar(150) NOT NULL,
  "postal_code" varchar(30) NOT NULL,
  "country_code" varchar(2) NOT NULL DEFAULT 'SK',
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "brands" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "slug" varchar(180) UNIQUE NOT NULL,
  "description" text,
  "logo_url" varchar(1000),
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "tax_classes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "rate_percent" decimal(5,2) NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" bigint,
  "name" varchar(150) NOT NULL,
  "slug" varchar(180) UNIQUE NOT NULL,
  "description" text,
  "image_url" varchar(1000),
  "sort_order" int NOT NULL DEFAULT 0,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "tags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "slug" varchar(120) UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brand_id" bigint,
  "tax_class_id" bigint,
  "created_by_user_id" bigint,
  "name" varchar(255) NOT NULL,
  "slug" varchar(280) UNIQUE NOT NULL,
  "short_description" varchar(500),
  "description" text,
  "status" product_status NOT NULL DEFAULT 'DRAFT',
  "featured" boolean NOT NULL DEFAULT false,
  "meta_title" varchar(255),
  "meta_description" varchar(500),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "product_categories" (
  "product_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  PRIMARY KEY ("product_id", "category_id")
);

CREATE TABLE "product_tags" (
  "product_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL,
  PRIMARY KEY ("product_id", "tag_id")
);

CREATE TABLE "product_options" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "name" varchar(100) NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0
);

CREATE TABLE "product_option_values" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "option_id" bigint NOT NULL,
  "value" varchar(100) NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0
);

CREATE TABLE "product_variants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "sku" varchar(100) UNIQUE NOT NULL,
  "name" varchar(255),
  "price" decimal(12,2) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'EUR',
  "active" boolean NOT NULL DEFAULT true,
  "weight_grams" int,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "variant_option_values" (
  "variant_id" bigint NOT NULL,
  "option_value_id" bigint NOT NULL,
  PRIMARY KEY ("variant_id", "option_value_id")
);

CREATE TABLE "product_images" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "variant_id" bigint,
  "image_url" varchar(1000) NOT NULL,
  "alt_text" varchar(255),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_primary" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "inventory_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "variant_id" bigint UNIQUE NOT NULL,
  "quantity_on_hand" int NOT NULL DEFAULT 0,
  "quantity_reserved" int NOT NULL DEFAULT 0,
  "reorder_level" int NOT NULL DEFAULT 0,
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "inventory_movements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventory_item_id" bigint NOT NULL,
  "movement_type" inventory_movement_type NOT NULL,
  "quantity_change" int NOT NULL,
  "reference_type" varchar(100),
  "reference_id" bigint,
  "note" varchar(500),
  "created_by_user_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "discounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_by_user_id" bigint,
  "name" varchar(255) NOT NULL,
  "description" text,
  "discount_type" discount_type NOT NULL,
  "application_type" discount_application_type NOT NULL,
  "value" decimal(12,2) NOT NULL,
  "minimum_order_amount" decimal(12,2),
  "maximum_discount_amount" decimal(12,2),
  "starts_at" timestamp,
  "ends_at" timestamp,
  "priority" int NOT NULL DEFAULT 0,
  "stackable" boolean NOT NULL DEFAULT false,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "discount_products" (
  "discount_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  PRIMARY KEY ("discount_id", "product_id")
);

CREATE TABLE "discount_categories" (
  "discount_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  PRIMARY KEY ("discount_id", "category_id")
);

CREATE TABLE "discount_tags" (
  "discount_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL,
  PRIMARY KEY ("discount_id", "tag_id")
);

CREATE TABLE "coupon_codes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "discount_id" bigint NOT NULL,
  "code" varchar(100) UNIQUE NOT NULL,
  "max_redemptions" int,
  "max_redemptions_per_user" int,
  "redemption_count" int NOT NULL DEFAULT 0,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "carts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "guest_session_id" bigint,
  "status" cart_status NOT NULL DEFAULT 'ACTIVE',
  "currency" varchar(3) NOT NULL DEFAULT 'EUR',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "cart_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" bigint NOT NULL,
  "variant_id" bigint NOT NULL,
  "quantity" int NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "cart_applied_coupons" (
  "cart_id" bigint NOT NULL,
  "coupon_code_id" bigint NOT NULL,
  "applied_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("cart_id", "coupon_code_id")
);

CREATE TABLE "wishlists" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "guest_session_id" bigint,
  "name" varchar(100) NOT NULL DEFAULT 'Saved',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "wishlist_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wishlist_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "variant_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "shipping_methods" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "description" varchar(500),
  "price" decimal(12,2) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'EUR',
  "estimated_min_days" int,
  "estimated_max_days" int,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_number" varchar(50) UNIQUE NOT NULL,
  "user_id" bigint,
  "guest_session_id" bigint,
  "shipping_method_id" bigint,
  "status" order_status NOT NULL DEFAULT 'PENDING_PAYMENT',
  "email" varchar(255) NOT NULL,
  "phone" varchar(50),
  "currency" varchar(3) NOT NULL DEFAULT 'EUR',
  "subtotal" decimal(12,2) NOT NULL,
  "discount_total" decimal(12,2) NOT NULL DEFAULT 0,
  "tax_total" decimal(12,2) NOT NULL DEFAULT 0,
  "shipping_total" decimal(12,2) NOT NULL DEFAULT 0,
  "grand_total" decimal(12,2) NOT NULL,
  "customer_note" text,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "paid_at" timestamp,
  "cancelled_at" timestamp
);

CREATE TABLE "order_addresses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "address_type" address_type NOT NULL,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "company" varchar(150),
  "phone" varchar(50),
  "street_line_1" varchar(255) NOT NULL,
  "street_line_2" varchar(255),
  "city" varchar(150) NOT NULL,
  "postal_code" varchar(30) NOT NULL,
  "country_code" varchar(2) NOT NULL
);

CREATE TABLE "order_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "variant_id" bigint NOT NULL,
  "sku" varchar(100) NOT NULL,
  "product_name" varchar(255) NOT NULL,
  "variant_name" varchar(255),
  "quantity" int NOT NULL,
  "unit_price" decimal(12,2) NOT NULL,
  "discount_total" decimal(12,2) NOT NULL DEFAULT 0,
  "tax_total" decimal(12,2) NOT NULL DEFAULT 0,
  "line_total" decimal(12,2) NOT NULL
);

CREATE TABLE "order_discounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "discount_id" bigint,
  "coupon_code_id" bigint,
  "name" varchar(255) NOT NULL,
  "amount_saved" decimal(12,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "discount_redemptions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "discount_id" bigint NOT NULL,
  "coupon_code_id" bigint,
  "user_id" bigint,
  "order_id" bigint NOT NULL,
  "amount_saved" decimal(12,2) NOT NULL,
  "redeemed_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "provider" varchar(100) NOT NULL,
  "provider_payment_id" varchar(255),
  "payment_method" varchar(100),
  "status" payment_status NOT NULL DEFAULT 'CREATED',
  "amount" decimal(12,2) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'EUR',
  "provider_metadata" jsonb,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "succeeded_at" timestamp,
  "failed_at" timestamp
);

CREATE TABLE "payment_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" bigint,
  "provider" varchar(100) NOT NULL,
  "provider_event_id" varchar(255) UNIQUE,
  "event_type" varchar(150) NOT NULL,
  "payload" jsonb,
  "processed" boolean NOT NULL DEFAULT false,
  "received_at" timestamp NOT NULL DEFAULT (now()),
  "processed_at" timestamp
);

CREATE TABLE "refunds" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "payment_id" bigint NOT NULL,
  "provider_refund_id" varchar(255),
  "amount" decimal(12,2) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'EUR',
  "status" refund_status NOT NULL DEFAULT 'PENDING',
  "reason" varchar(500),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "completed_at" timestamp
);

CREATE TABLE "shipments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "status" shipment_status NOT NULL DEFAULT 'CREATED',
  "carrier" varchar(150),
  "tracking_number" varchar(255),
  "tracking_url" varchar(1000),
  "shipped_at" timestamp,
  "delivered_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "product_reviews" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "order_item_id" bigint,
  "rating" int NOT NULL,
  "title" varchar(255),
  "comment" text,
  "approved" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "admin_audit_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "action" varchar(150) NOT NULL,
  "entity_type" varchar(100),
  "entity_id" bigint,
  "old_data" jsonb,
  "new_data" jsonb,
  "ip_address" varchar(100),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "site_settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "setting_key" varchar(150) UNIQUE NOT NULL,
  "setting_value" text,
  "updated_by_user_id" bigint,
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "auth_accounts" ("provider", "provider_account_id");

CREATE INDEX ON "auth_accounts" ("user_id");

CREATE INDEX ON "guest_sessions" ("session_token");

CREATE INDEX ON "guest_sessions" ("converted_user_id");

CREATE INDEX ON "addresses" ("user_id");

CREATE INDEX ON "categories" ("parent_id");

CREATE INDEX ON "categories" ("slug");

CREATE INDEX ON "products" ("slug");

CREATE INDEX ON "products" ("brand_id");

CREATE INDEX ON "products" ("status");

CREATE INDEX ON "products" ("featured");

CREATE INDEX ON "product_categories" ("category_id");

CREATE INDEX ON "product_tags" ("tag_id");

CREATE INDEX ON "product_options" ("product_id");

CREATE INDEX ON "product_option_values" ("option_id");

CREATE UNIQUE INDEX ON "product_option_values" ("option_id", "value");

CREATE INDEX ON "product_variants" ("product_id");

CREATE INDEX ON "product_variants" ("sku");

CREATE INDEX ON "product_variants" ("price");

CREATE INDEX ON "variant_option_values" ("option_value_id");

CREATE INDEX ON "product_images" ("product_id");

CREATE INDEX ON "product_images" ("variant_id");

CREATE INDEX ON "inventory_movements" ("inventory_item_id");

CREATE INDEX ON "inventory_movements" ("created_at");

CREATE INDEX ON "discounts" ("active");

CREATE INDEX ON "discounts" ("starts_at");

CREATE INDEX ON "discounts" ("ends_at");

CREATE INDEX ON "discount_products" ("product_id");

CREATE INDEX ON "discount_categories" ("category_id");

CREATE INDEX ON "discount_tags" ("tag_id");

CREATE INDEX ON "coupon_codes" ("code");

CREATE INDEX ON "coupon_codes" ("discount_id");

CREATE INDEX ON "carts" ("user_id");

CREATE INDEX ON "carts" ("guest_session_id");

CREATE INDEX ON "carts" ("status");

CREATE UNIQUE INDEX ON "cart_items" ("cart_id", "variant_id");

CREATE INDEX ON "cart_items" ("variant_id");

CREATE INDEX ON "wishlists" ("user_id");

CREATE INDEX ON "wishlists" ("guest_session_id");

CREATE UNIQUE INDEX ON "wishlist_items" ("wishlist_id", "product_id", "variant_id");

CREATE INDEX ON "wishlist_items" ("product_id");

CREATE INDEX ON "orders" ("order_number");

CREATE INDEX ON "orders" ("user_id");

CREATE INDEX ON "orders" ("status");

CREATE INDEX ON "orders" ("created_at");

CREATE INDEX ON "order_addresses" ("order_id");

CREATE INDEX ON "order_items" ("order_id");

CREATE INDEX ON "order_items" ("product_id");

CREATE INDEX ON "order_items" ("variant_id");

CREATE INDEX ON "order_discounts" ("order_id");

CREATE INDEX ON "discount_redemptions" ("discount_id");

CREATE INDEX ON "discount_redemptions" ("coupon_code_id");

CREATE INDEX ON "discount_redemptions" ("user_id");

CREATE INDEX ON "discount_redemptions" ("order_id");

CREATE INDEX ON "payments" ("order_id");

CREATE INDEX ON "payments" ("provider_payment_id");

CREATE INDEX ON "payments" ("status");

CREATE INDEX ON "payment_events" ("payment_id");

CREATE INDEX ON "payment_events" ("provider_event_id");

CREATE INDEX ON "payment_events" ("processed");

CREATE INDEX ON "refunds" ("order_id");

CREATE INDEX ON "refunds" ("payment_id");

CREATE INDEX ON "refunds" ("status");

CREATE INDEX ON "shipments" ("order_id");

CREATE INDEX ON "shipments" ("tracking_number");

CREATE INDEX ON "product_reviews" ("product_id");

CREATE INDEX ON "product_reviews" ("user_id");

CREATE INDEX ON "product_reviews" ("approved");

CREATE INDEX ON "admin_audit_logs" ("admin_user_id");

CREATE INDEX ON "admin_audit_logs" ("entity_type");

CREATE INDEX ON "admin_audit_logs" ("entity_id");

CREATE INDEX ON "admin_audit_logs" ("created_at");

COMMENT ON TABLE "users" IS 'Main user account.
Do not store raw passwords here.
Authentication data lives in auth_accounts.
';

COMMENT ON TABLE "roles" IS 'Example roles:
CUSTOMER
ADMIN
MANAGER
SUPPORT
';

COMMENT ON TABLE "auth_accounts" IS 'LOCAL:
  provider_account_id can be user''s email
  password_hash contains BCrypt/Argon2 hash.

GOOGLE:
  provider_account_id is Google''s user/sub ID
  password_hash is NULL.
';

COMMENT ON TABLE "auth_tokens" IS 'Used for email verification and password reset.
Store hash of token, not raw token.
';

COMMENT ON TABLE "guest_sessions" IS 'Anonymous visitor.

Used for guest cart and guest wishlist.
After registration/login, data can be merged into user account.
';

COMMENT ON TABLE "tax_classes" IS 'Example:
Standard Slovakia VAT
rate_percent = 23.00

Exact rates should be maintained by admin/configuration.
';

COMMENT ON TABLE "categories" IS 'Self-referencing hierarchy.

Example:

Electronics
  -> Computers
      -> Laptops

parent_id = NULL means root category.
';

COMMENT ON TABLE "products" IS 'Product itself does NOT contain stock or price.

Price/SKU/stock belong to product_variants.

Even a product without options should have one Default variant.
';

COMMENT ON TABLE "product_variants" IS 'Examples:

Product: T-Shirt

Variant 1:
Black / M
SKU: TSHIRT-BLK-M

Variant 2:
Black / L
SKU: TSHIRT-BLK-L

For product without options:
name = Default
';

COMMENT ON TABLE "product_images" IS 'variant_id can be NULL for general product images.

If variant_id is specified,
image can belong specifically to e.g. Black variant.
';

COMMENT ON TABLE "inventory_items" IS 'Available stock:

quantity_on_hand - quantity_reserved
';

COMMENT ON TABLE "inventory_movements" IS 'Gives complete history of stock changes.

+10 = stock added
-2  = stock removed
';

COMMENT ON TABLE "discounts" IS 'Examples:

PERCENTAGE + value 20 = -20%

FIXED_AMOUNT + value 15 = -15 EUR

Can target:
products,
categories,
tags.
';

COMMENT ON TABLE "carts" IS 'Cart has exactly one owner:

either user_id
OR guest_session_id.

Backend should enforce that both are not populated simultaneously.
';

COMMENT ON TABLE "wishlists" IS 'Same ownership rule as cart:
either user or guest.
';

COMMENT ON TABLE "orders" IS 'Monetary values are snapshots.

Never calculate old orders from current product prices.
';

COMMENT ON TABLE "order_addresses" IS 'Snapshot of shipping/billing address.

Do not reference user address directly,
because user can change it after placing order.
';

COMMENT ON TABLE "order_items" IS 'Snapshot data.

Even if product name/price changes later,
order history remains unchanged.
';

COMMENT ON TABLE "payments" IS 'provider examples:
STRIPE
GOPAY
TRUSTPAY

payment_method examples:
CARD
GOOGLE_PAY
BANK_TRANSFER
';

COMMENT ON TABLE "payment_events" IS 'Stores Stripe/other provider webhook events.

Useful for debugging and webhook idempotency.
';

COMMENT ON TABLE "product_reviews" IS 'Backend should validate rating from 1 to 5.
order_item_id can be used for Verified Purchase.
';

COMMENT ON TABLE "admin_audit_logs" IS 'Examples:

PRODUCT_CREATED
PRODUCT_UPDATED
DISCOUNT_CREATED
USER_BLOCKED
ORDER_REFUNDED
';

COMMENT ON TABLE "site_settings" IS 'For small configurable settings.

Examples:
store_name
support_email
free_shipping_threshold
maintenance_mode
';

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auth_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auth_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "guest_sessions" ADD FOREIGN KEY ("converted_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("tax_class_id") REFERENCES "tax_classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_categories" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_tags" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_options" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_option_values" ADD FOREIGN KEY ("option_id") REFERENCES "product_options" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "variant_option_values" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "variant_option_values" ADD FOREIGN KEY ("option_value_id") REFERENCES "product_option_values" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movements" ADD FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movements" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discounts" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_products" ADD FOREIGN KEY ("discount_id") REFERENCES "discounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_products" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_categories" ADD FOREIGN KEY ("discount_id") REFERENCES "discounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_tags" ADD FOREIGN KEY ("discount_id") REFERENCES "discounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "coupon_codes" ADD FOREIGN KEY ("discount_id") REFERENCES "discounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carts" ADD FOREIGN KEY ("guest_session_id") REFERENCES "guest_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_applied_coupons" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_applied_coupons" ADD FOREIGN KEY ("coupon_code_id") REFERENCES "coupon_codes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlists" ADD FOREIGN KEY ("guest_session_id") REFERENCES "guest_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("wishlist_id") REFERENCES "wishlists" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("guest_session_id") REFERENCES "guest_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("shipping_method_id") REFERENCES "shipping_methods" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_addresses" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_discounts" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_discounts" ADD FOREIGN KEY ("discount_id") REFERENCES "discounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_discounts" ADD FOREIGN KEY ("coupon_code_id") REFERENCES "coupon_codes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_redemptions" ADD FOREIGN KEY ("discount_id") REFERENCES "discounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_redemptions" ADD FOREIGN KEY ("coupon_code_id") REFERENCES "coupon_codes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_redemptions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_redemptions" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment_events" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "refunds" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "refunds" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shipments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_reviews" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_reviews" ADD FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "admin_audit_logs" ADD FOREIGN KEY ("admin_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "site_settings" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
